// The WebAuthn data service over PostgreSQL: webauthn.data.Service served
// with connect-go, its statements generated by sqlc over pgx.
package main

import (
	"os"

	"github.com/authaas/webauthn-data-service-postgres-pgx-connect-go/internal/cli"
)

func main() {
	os.Exit(cli.Run())
}
